---
- name: config Web VM with Docker
  hosts: webservers
  become: true
  tasks:
    - name: docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present
        
    - name: install pip3
      apt:
        name: python3-pip
        force_apt_get: yes
        state: present
        
    - name: install docker python module
      pip:
        name: docker
        state: present
    - name: download and launch a docker web container
      docker container:
        name: dvwa
        image: cybersecurity/dvwa
        start: started
        restart_policy: always
        published_ports: 80:80
    - name: enable docker service
      systemd:
        name: docker
        enabled: yes
